# Generated by Django 4.1.5 on 2023-02-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.FloatField()),
                ('target', models.IntegerField()),
                ('is_like', models.BooleanField()),
            ],
        ),
    ]
