# Generated by Django 4.1.5 on 2023-02-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='is_like',
        ),
        migrations.AddField(
            model_name='rewards',
            name='like_or_comment',
            field=models.CharField(choices=[('like', 'LIKE'), ('comment', 'COMMENT')], default='like', max_length=7),
            preserve_default=False,
        ),
    ]
