# Generated by Django 4.1.5 on 2023-02-13 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_rewards_is_like_rewards_like_or_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='target',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='token',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
