# Generated by Django 4.1.5 on 2023-02-13 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_rewards_target_alter_rewards_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='token',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
