# Generated by Django 4.1.5 on 2023-02-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_rewards_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rewards',
            unique_together={('target', 'like_or_comment')},
        ),
    ]
