# Generated by Django 4.1.5 on 2023-02-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_rewards_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewards',
            old_name='like_or_comment',
            new_name='target_type',
        ),
        migrations.AlterUniqueTogether(
            name='rewards',
            unique_together={('target', 'target_type')},
        ),
    ]
