# Generated by Django 4.1.5 on 2023-02-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_contentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rewarded', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.rewards')),
            ],
        ),
    ]
