# Generated by Django 4.1.5 on 2023-02-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_contentrewards'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentrewards',
            unique_together={('content', 'reward')},
        ),
    ]
