# Generated by Django 4.1.5 on 2023-03-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_rewards_reward_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='content.contentcategory'),
            preserve_default=False,
        ),
    ]
