# Generated by Django 4.1.5 on 2023-03-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_content_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrewards',
            name='transaction_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
